/**
 * Media Routes
 * 
 * API endpoints for media retrieval and management.
 */
import { FastifyInstance, FastifyPluginAsync, FastifyReply, FastifyRequest } from 'fastify';
import fp from 'fastify-plugin';
import { mediaRepository } from '../../repositories/media-repository';
import { uploadService } from '../../services/media/upload/service';
// TODO: Import access service once implemented
// import { accessService } from '../../services/media/access/service';

/**
 * Types for request parameters
 */
interface GetMediaRequest {
  Params: {
    id: string;
  };
  Querystring: {
    variant?: string;
    width?: number;
    height?: number;
    format?: string;
    download?: boolean;
  };
}

interface GetMediaByUserRequest {
  Params: {
    userId: string;
  };
  Querystring: {
    limit?: number;
    offset?: number;
    status?: string;
    mimeType?: string;
  };
}

interface DeleteMediaRequest {
  Params: {
    id: string;
  };
}

/**
 * Media routes plugin
 */
export const mediaRoutes: FastifyPluginAsync = async (fastify: FastifyInstance) => {
  
  // Get media file by ID
  fastify.get<GetMediaRequest>('/:id', {
    schema: {
      description: 'Get a media file by ID',
      tags: ['media'],
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { type: 'string' }
        }
      },
      querystring: {
        type: 'object',
        properties: {
          variant: { type: 'string' },
          width: { type: 'number' },
          height: { type: 'number' },
          format: { type: 'string' },
          download: { type: 'boolean' }
        }
      },
      response: {
        200: {
          description: 'Success response with media file details',
          type: 'object',
          properties: {
            data: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                user_id: { type: 'string' },
                original_name: { type: 'string' },
                mimeType: { type: 'string' },
                size: { type: 'number' },
                status: { type: 'string' },
                created_at: { type: 'string' },
                urls: {
                  type: 'object',
                  properties: {
                    original: { type: 'string' },
                    thumbnail: { type: 'string' },
                    small: { type: 'string' },
                    medium: { type: 'string' },
                    large: { type: 'string' }
                  }
                }
              }
            },
            meta: {
              type: 'object',
              properties: {
                timestamp: { type: 'string' },
                requestId: { type: 'string' }
              }
            }
          }
        }
      }
    },
    handler: async (request, reply) => {
      try {
        const { id } = request.params;
        
        // Get media file
        const mediaFile = await mediaRepository.findById(id);
        if (!mediaFile) {
          return reply.code(404).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'RESOURCE_NOT_FOUND',
              message: 'Media file not found'
            }]
          });
        }
        
        // TODO: Check access permission when access service is implemented
        // For now, just check if file is not deleted
        if (mediaFile.status === 'deleted') {
          return reply.code(404).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'RESOURCE_NOT_FOUND',
              message: 'Media file not found'
            }]
          });
        }
        
        // Build URLs for all variants
        const urls: Record<string, string> = {};
        
        // Add original URL (for now just a placeholder URL)
        // This would be generated by the storage or delivery service
        urls.original = `/api/v1/media/${id}/content`;
        
        // Add variant URLs if available
        if (mediaFile.variants) {
          Object.entries(mediaFile.variants).forEach(([name, variant]) => {
            urls[name] = `/api/v1/media/${id}/content?variant=${name}`;
          });
        }
        
        return reply.send({
          data: {
            id: mediaFile.id,
            user_id: mediaFile.user_id,
            original_name: mediaFile.original_name,
            mimeType: mediaFile.mimeType,
            size: mediaFile.size,
            status: mediaFile.status,
            created_at: mediaFile.created_at.toISOString(),
            urls
          },
          meta: {
            timestamp: new Date().toISOString(),
            requestId: request.id
          }
        });
      } catch (error) {
        request.log.error('Error getting media file', { error });
        throw error;
      }
    }
  });
  
  // Get media file content
  fastify.get<GetMediaRequest>('/:id/content', {
    schema: {
      description: 'Get media file content',
      tags: ['media'],
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { type: 'string' }
        }
      },
      querystring: {
        type: 'object',
        properties: {
          variant: { type: 'string' },
          width: { type: 'number' },
          height: { type: 'number' },
          format: { type: 'string' },
          download: { type: 'boolean' }
        }
      }
    },
    handler: async (request, reply) => {
      try {
        const { id } = request.params;
        const { variant, download } = request.query;
        
        // Get media file
        const mediaFile = await mediaRepository.findById(id);
        if (!mediaFile) {
          return reply.code(404).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'RESOURCE_NOT_FOUND',
              message: 'Media file not found'
            }]
          });
        }
        
        // TODO: Check access permission when access service is implemented
        // For now, just check if file is not deleted
        if (mediaFile.status === 'deleted') {
          return reply.code(404).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'RESOURCE_NOT_FOUND',
              message: 'Media file not found'
            }]
          });
        }
        
        // Get file path
        let filePath: string;
        
        if (variant && mediaFile.variants && mediaFile.variants[variant]) {
          // Use variant if specified and available
          filePath = mediaFile.variants[variant].path;
        } else {
          // Use original file
          filePath = mediaFile.path;
        }
        
        // TODO: Implement stream and transformation when processing service is implemented
        // For now, just return a placeholder response
        
        reply.type(mediaFile.mimeType);
        
        // Set download header if requested
        if (download) {
          reply.header('Content-Disposition', `attachment; filename="${mediaFile.original_name}"`);
        }
        
        // Set cache control headers
        reply.header('Cache-Control', 'public, max-age=31536000');
        
        // Return a placeholder message
        return reply.send(`Media content for ${id} would be served here. Implementation pending.`);
      } catch (error) {
        request.log.error('Error getting media content', { error });
        throw error;
      }
    }
  });
  
  // Get media files by user
  fastify.get<GetMediaByUserRequest>('/user/:userId', {
    schema: {
      description: 'Get media files by user',
      tags: ['media'],
      params: {
        type: 'object',
        required: ['userId'],
        properties: {
          userId: { type: 'string' }
        }
      },
      querystring: {
        type: 'object',
        properties: {
          limit: { type: 'number' },
          offset: { type: 'number' },
          status: { type: 'string' },
          mimeType: { type: 'string' }
        }
      },
      response: {
        200: {
          description: 'Success response with media files',
          type: 'object',
          properties: {
            data: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string' },
                  original_name: { type: 'string' },
                  mimeType: { type: 'string' },
                  size: { type: 'number' },
                  status: { type: 'string' },
                  created_at: { type: 'string' },
                  urls: {
                    type: 'object',
                    properties: {
                      original: { type: 'string' },
                      thumbnail: { type: 'string' }
                    }
                  }
                }
              }
            },
            meta: {
              type: 'object',
              properties: {
                timestamp: { type: 'string' },
                requestId: { type: 'string' },
                pagination: {
                  type: 'object',
                  properties: {
                    total: { type: 'number' },
                    limit: { type: 'number' },
                    offset: { type: 'number' }
                  }
                }
              }
            }
          }
        }
      }
    },
    preHandler: [fastify.authenticate], // Require authentication
    handler: async (request, reply) => {
      try {
        const { userId } = request.params;
        const { limit = 10, offset = 0, status, mimeType } = request.query;
        
        // Check if requesting user is the same as the user ID or has admin privileges
        if (request.user.id !== userId && !request.user.roles?.includes('admin')) {
          return reply.code(403).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'FORBIDDEN',
              message: 'Not authorized to access these media files'
            }]
          });
        }
        
        // Get media files
        const mediaFiles = await mediaRepository.findByUserId(userId, {
          limit: Number(limit),
          offset: Number(offset),
          status,
          mimeType
        });
        
        // Get total count for pagination
        const total = await mediaRepository.countByUser(userId);
        
        // Transform to response format
        const data = mediaFiles.map(file => {
          // Build URLs
          const urls: Record<string, string> = {
            original: `/api/v1/media/${file.id}/content`
          };
          
          // Add thumbnail if available
          if (file.variants && file.variants.thumbnail) {
            urls.thumbnail = `/api/v1/media/${file.id}/content?variant=thumbnail`;
          }
          
          return {
            id: file.id,
            original_name: file.original_name,
            mimeType: file.mimeType,
            size: file.size,
            status: file.status,
            created_at: file.created_at.toISOString(),
            urls
          };
        });
        
        return reply.send({
          data,
          meta: {
            timestamp: new Date().toISOString(),
            requestId: request.id,
            pagination: {
              total,
              limit: Number(limit),
              offset: Number(offset)
            }
          }
        });
      } catch (error) {
        request.log.error('Error getting media files by user', { error });
        throw error;
      }
    }
  });
  
  // Delete media file
  fastify.delete<DeleteMediaRequest>('/:id', {
    schema: {
      description: 'Delete a media file',
      tags: ['media'],
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { type: 'string' }
        }
      },
      response: {
        200: {
          description: 'Success response',
          type: 'object',
          properties: {
            data: {
              type: 'object',
              properties: {
                success: { type: 'boolean' }
              }
            },
            meta: {
              type: 'object',
              properties: {
                timestamp: { type: 'string' },
                requestId: { type: 'string' }
              }
            }
          }
        }
      }
    },
    preHandler: [fastify.authenticate], // Require authentication
    handler: async (request, reply) => {
      try {
        const { id } = request.params;
        
        // Get media file to check ownership
        const mediaFile = await mediaRepository.findById(id);
        if (!mediaFile) {
          return reply.code(404).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'RESOURCE_NOT_FOUND',
              message: 'Media file not found'
            }]
          });
        }
        
        // Check ownership or admin privileges
        if (mediaFile.user_id !== request.user.id && !request.user.roles?.includes('admin')) {
          return reply.code(403).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'FORBIDDEN',
              message: 'Not authorized to delete this media file'
            }]
          });
        }
        
        // Delete media
        const success = await uploadService.deleteMedia(id);
        
        return reply.send({
          data: {
            success
          },
          meta: {
            timestamp: new Date().toISOString(),
            requestId: request.id
          }
        });
      } catch (error) {
        request.log.error('Error deleting media file', { error });
        throw error;
      }
    }
  });
  
  // Get user storage usage
  fastify.get('/user/:userId/storage-usage', {
    schema: {
      description: 'Get user storage usage',
      tags: ['media'],
      params: {
        type: 'object',
        required: ['userId'],
        properties: {
          userId: { type: 'string' }
        }
      },
      response: {
        200: {
          description: 'Success response with storage usage',
          type: 'object',
          properties: {
            data: {
              type: 'object',
              properties: {
                totalSize: { type: 'number' },
                fileCount: { type: 'number' },
                formattedSize: { type: 'string' }
              }
            },
            meta: {
              type: 'object',
              properties: {
                timestamp: { type: 'string' },
                requestId: { type: 'string' }
              }
            }
          }
        }
      }
    },
    preHandler: [fastify.authenticate], // Require authentication
    handler: async (request, reply) => {
      try {
        const { userId } = request.params;
        
        // Check if requesting user is the same as the user ID or has admin privileges
        if (request.user.id !== userId && !request.user.roles?.includes('admin')) {
          return reply.code(403).send({
            data: null,
            meta: {
              timestamp: new Date().toISOString(),
              requestId: request.id
            },
            errors: [{
              code: 'FORBIDDEN',
              message: 'Not authorized to access this storage usage information'
            }]
          });
        }
        
        // Get storage usage
        const totalSize = await mediaRepository.getUserStorageUsage(userId);
        const fileCount = await mediaRepository.countByUser(userId);
        
        // Format size for display
        let formattedSize = '';
        if (totalSize < 1024) {
          formattedSize = `${totalSize} bytes`;
        } else if (totalSize < 1024 * 1024) {
          formattedSize = `${(totalSize / 1024).toFixed(1)} KB`;
        } else if (totalSize < 1024 * 1024 * 1024) {
          formattedSize = `${(totalSize / (1024 * 1024)).toFixed(1)} MB`;
        } else {
          formattedSize = `${(totalSize / (1024 * 1024 * 1024)).toFixed(1)} GB`;
        }
        
        return reply.send({
          data: {
            totalSize,
            fileCount,
            formattedSize
          },
          meta: {
            timestamp: new Date().toISOString(),
            requestId: request.id
          }
        });
      } catch (error) {
        request.log.error('Error getting storage usage', { error });
        throw error;
      }
    }
  });
};

export default fp(mediaRoutes);
