import 'dotenv/config'; // Load environment variables
import { db } from '../database'; // Adjusted path
import { media } from '../database/schema/media'; // Adjusted path
import { blobService } from '../services/blob'; // Adjusted path
import { Logger } from 'pino';
import { readFile } from 'fs/promises';
import path from 'path';
import { eq, isNull, asc, gt, and, SQL } from 'drizzle-orm'; // Added and, SQL imports

// Placeholder for logger import (adjust path as needed)
let logger: Logger;
try {
  const loggerModule = require('../lib/logger.js'); // Using require for CommonJS
  logger = loggerModule.logger;
} catch (e) {
  console.warn("Logger module not found at '../lib/logger.js', using console.", e);
  logger = console as any;
}

const BATCH_SIZE = 100;
// IMPORTANT: Set MEDIA_DIRECTORY in your .env file to the path of your existing media files
const MEDIA_DIR = process.env.MEDIA_DIRECTORY;

if (!MEDIA_DIR) {
    logger.error("MEDIA_DIRECTORY environment variable is not set. Cannot run migration.");
    process.exit(1);
}

async function migrateMediaToBlobStorage() {
  let processed = 0;
  let migrated = 0;
  let failed = 0;
  let hasMore = true;
  // Using cursor-based pagination is generally more robust than offset
  let lastProcessedId: string | null = null;

  logger.info(`Starting media migration to Vercel Blob from directory: ${MEDIA_DIR}`);

  while (hasMore) {
    try {
        // Build conditions array
        const conditions: SQL[] = [isNull(media.blobUrl)]; // Start with the base condition

        // Apply cursor condition if not the first batch
        if (lastProcessedId) {
            // This assumes IDs are sortable strings (like UUIDs or timestamps)
            // Adjust if your IDs are different (e.g., numeric)
            conditions.push(gt(media.id, lastProcessedId));
        }

        // Build and execute the query with all conditions
        const mediaItems = await db
            .select()
            .from(media)
            .where(and(...conditions)) // Apply all conditions using and()
            .orderBy(asc(media.id))    // Order by ID for cursor
            .limit(BATCH_SIZE);

        if (mediaItems.length === 0) {
          logger.info('No more media items found to migrate in this batch.');
          hasMore = false;
          break;
        }

        logger.info(`Processing batch of ${mediaItems.length} media items...`);
        hasMore = mediaItems.length === BATCH_SIZE; // Check if there might be more

        for (const item of mediaItems) {
          processed++;
          lastProcessedId = item.id; // Update cursor for the next batch

          try {
            // Construct the expected path in the legacy system
            // IMPORTANT: This assumes the filename in MEDIA_DIR is exactly the item.id
            // Adjust this logic if your file naming convention is different (e.g., item.id + extension)
            // Add non-null assertion '!' as MEDIA_DIR is checked at the start
            const filePath = path.join(MEDIA_DIR!, item.id);
            logger.debug(`Attempting to read file: ${filePath}`);

            // Read file from the legacy location
            const fileBuffer = await readFile(filePath);
            logger.debug(`Read file successfully: ${filePath}, size: ${fileBuffer.length}`);

            // Upload to Vercel Blob using the BlobService
            const blobResult = await blobService.uploadFile(
              fileBuffer,
              item.originalName, // Use original name for upload context
              {
                contentType: item.mimeType,
                access: 'public', // Assuming media should be public
                addRandomSuffix: false // Use the structured path generated by BlobService
              },
              item.userId // Pass userId for path organization in BlobService
            );

            logger.debug(`Uploaded to blob: ${blobResult.url}, path: ${blobResult.pathname}`);

            // Update database record with new blob URL and path
            await db
              .update(media)
              .set({
                blobUrl: blobResult.url,
                blobPath: blobResult.pathname // Store the path used in Vercel Blob
              })
              .where(eq(media.id, item.id));

            migrated++;
            logger.info(`Migrated media item ${item.id} to blob: ${blobResult.url}`);

          } catch (error) {
            failed++;
            const errorMsg = error instanceof Error ? error.message : String(error);
            logger.error(`Failed to migrate media item ${item.id}`, { error: errorMsg });
            // Decide if you want to continue or stop on failure
            // continue;
          }

          // Log progress periodically
          if (processed % 10 === 0) {
            logger.info('Migration progress', { processed, migrated, failed, lastId: lastProcessedId });
          }
        } // End for loop

    } catch (dbError) {
        // Handle potential errors during the database query itself
        const errorMsg = dbError instanceof Error ? dbError.message : String(dbError);
        logger.error('Error fetching batch of media items from database', { error: errorMsg });
        // Consider adding a delay and retry mechanism or stopping the migration
        hasMore = false; // Stop processing if DB query fails
    }

  } // End while loop

  logger.info('Media migration to Vercel Blob completed.', {
    totalItemsProcessed: processed,
    successfullyMigrated: migrated,
    failedMigrations: failed
  });
}

// --- Execution ---
// Ensure environment variables are loaded and run the migration
migrateMediaToBlobStorage()
  .then(() => {
    logger.info('Migration script finished successfully.');
    process.exit(0);
  })
  .catch((error) => {
    const errorMsg = error instanceof Error ? error.message : String(error);
    logger.error('Migration script failed with unhandled error:', { error: errorMsg });
    process.exit(1);
  });
